name: Release
on:
  release:
    types: [edited, published]
    branches:
      - main
      - feature-*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build image
        uses: Nature40/pimod@master
        with:
          pifile: pi-gadget.Pifile

      - name: Make tarball
        run: |
          tar -czvf pi-gadget.tar.gz pi-gadget.img

      - name: Publish binaries  
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'pi-gadget.tar.gz'